### ISSUE TITLE
Add method option

### ISSUE THREAD

**Issue by ocervell** [topscoder/fourohme#2]
Allow to use other HTTP verbs than `get`: `post`, `put`, `update`, `delete`, etc...

**Comment by topscoder** [comment]
These HTTP verbs are already implemented: "GET", "POST", "HEAD", "DELETE", "PUT", "PATCH", "OPTIONS", "TRACE", "TRACK"

Source: https://github.com/topscoder/fourohme/blob/b07215273f84d85f9896f815fe93bfa7a2055322/fourohme.go#L197
